In [2]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime as dt
import datetime
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
# %matplotlib inline
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Convolution1D, MaxPooling1D
from sklearn.model_selection import train_test_split

# import os
# os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'


class myclass():
    def __init__(self, model_stock):
        self.model_stock = model_stock

    def main(self):
        train_X = np.load('preprocess_data/{}_train_X.npy'.format(self.model_stock))
        train_Y = np.load('preprocess_data/{}_train_Y.npy'.format(self.model_stock))
        print(train_X)
        print(train_Y)
        print(train_X.shape)
        print(train_Y.shape)
        print(train_X.shape[1:])
        print(type(train_X))
        print(type(train_Y))


        model = Sequential()
        
        model.add(Convolution1D(64, 8, padding='same', activation='relu', 
                                input_shape=train_X.shape[1:]))
        model.add(Convolution1D(64, 8, activation='relu'))
        model.add(MaxPooling1D(pool_size=(2)))
        model.add(Dropout(0.25))
        
        model.add(Convolution1D(32, 8, activation='relu', padding='same'))
        model.add(Convolution1D(32, 8, activation='relu'))
        model.add(MaxPooling1D(pool_size=(2)))
        model.add(Dropout(0.25))
        
        model.add(Flatten())
        
        model.add(Dense(512, activation='relu'))
        model.add(Dropout(0.5))
        model.add(Dense(1, activation= 'sigmoid'))
        
        
        
        model.compile(loss='mse', optimizer='adam', metrics=['mse'])

        
        model.summary()
        
        epochs = 100
        history = model.fit(train_X, train_Y, validation_split=0.1, epochs=epochs)

        plt.plot(range(epochs), history.history['loss'], label='loss')
        plt.plot(range(epochs), history.history['val_loss'], label='val_loss')
        plt.xlabel('epoch')
        plt.ylabel('loss')
        plt.legend() 
        plt.show()




myclass = myclass('nasdaq100')
myclass.main()

[[[0.64243491 0.62600436 0.67632493 ... 0.17940505 0.26168816 0.6434143 ]
  [0.60740606 0.5917109  0.63554903 ... 0.14707278 0.24537799 0.63542872]
  [0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  ...
  [0.44035054 0.4605424  0.53411525 ... 0.20655096 0.23957865 0.66121496]
  [0.44369747 0.45450544 0.51509143 ... 0.20001832 0.231371   0.65399722]
  [0.43048494 0.44583996 0.51626454 ... 0.20504928 0.22966431 0.65831036]]

 [[0.60740606 0.5917109  0.63554903 ... 0.14707278 0.24537799 0.63542872]
  [0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  [0.60425068 0.68312653 0.64749019 ... 0.11640619 0.21323003 0.62383063]
  ...
  [0.44369747 0.45450544 0.51509143 ... 0.20001832 0.231371   0.65399722]
  [0.43048494 0.44583996 0.51626454 ... 0.20504928 0.22966431 0.65831036]
  [0.43951301 0.44373564 0.51750138 ... 0.20722225 0.22620295 0.65961484]]

 [[0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  [0.60425068 0.683126

KeyboardInterrupt: 