In [15]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime as dt
import datetime
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
# %matplotlib inline
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import GlobalMaxPooling1D
from sklearn.model_selection import train_test_split

# import os
# os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'


class myclass():
    def __init__(self, model_stock):
        self.model_stock = model_stock

    def main(self):
        train_X = np.load('preprocess_data/{}_train_X.npy'.format(self.model_stock))
        train_Y = np.load('preprocess_data/{}_train_Y.npy'.format(self.model_stock))
        print(train_X)
        print(train_Y)
        print(train_X.shape)
        print(train_Y.shape)
        print(train_X.shape[1:])
        print(type(train_X))
        print(type(train_Y))

        # trainデータからvalidデータを分割
        X_train, X_valid, y_train, y_valid = train_test_split(
            train_X,
            train_Y,
            random_state = 0,
            test_size = 0.2
        )
        print(X_train.shape, y_train.shape, X_valid.shape, y_valid.shape) 
       
        model = Sequential()
        model.add(Conv1D(32, 3, activation='relu',input_shape=(64,32)))
        model.add(Dense(16,activation='relu'))
        model.add(Flatten())
        model.add(Dense(1))
        model.compile(loss="mse", optimizer="adam")


#         model = Sequential()
#         model.add(Conv1D(64, 8, padding='same', input_shape=(64, 32), activation='relu'))
#         model.add(MaxPooling1D(2, padding='same'))
#         model.add(Conv1D(64, 8, padding='same', activation='relu'))
#         model.add(MaxPooling1D(2, padding='same'))
#         model.add(Conv1D(32, 8, padding='same', activation='relu'))
#         model.add(MaxPooling1D(2, padding='same'))
        
        
#         model.add(Flatten())
#         model.add(Dense(64, activation='relu'))
#         model.add(Dense(1))

#         model.compile(loss='mse', optimizer='adam')

#        
#         channel_size = 8
#         kernel_size = 10

#         model = Sequential()
#         model.add( Conv1D(filters=channel_size, kernel_size=kernel_size,
#                               strides=1, padding="same", activation="relu",
#                               input_shape=(64, 32) ) )
#         model.add( Conv1D(filters=1, kernel_size=8, padding='same', activation='tanh' ) )
#         model.add( GlobalMaxPooling1D() )

#         model.compile(loss='mse', optimizer='adam')
        model.summary()

        
 
        history = model.fit(X_train, y_train, epochs=20, batch_size=100, verbose=1, validation_data=(X_valid, y_valid))
        
#         epochs = 100
#         history = model.fit(train_X, train_Y, validation_split=0.1, epochs=epochs)

#         plt.plot(range(epochs), history.history['loss'], label='loss')
#         plt.plot(range(epochs), history.history['val_loss'], label='val_loss')
#         plt.xlabel('epoch')
#         plt.ylabel('loss')
#         plt.legend() 
#         plt.show()




myclass = myclass('nasdaq100')
myclass.main()

[[[0.64243491 0.62600436 0.67632493 ... 0.17940505 0.26168816 0.6434143 ]
  [0.60740606 0.5917109  0.63554903 ... 0.14707278 0.24537799 0.63542872]
  [0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  ...
  [0.44035054 0.4605424  0.53411525 ... 0.20655096 0.23957865 0.66121496]
  [0.44369747 0.45450544 0.51509143 ... 0.20001832 0.231371   0.65399722]
  [0.43048494 0.44583996 0.51626454 ... 0.20504928 0.22966431 0.65831036]]

 [[0.60740606 0.5917109  0.63554903 ... 0.14707278 0.24537799 0.63542872]
  [0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  [0.60425068 0.68312653 0.64749019 ... 0.11640619 0.21323003 0.62383063]
  ...
  [0.44369747 0.45450544 0.51509143 ... 0.20001832 0.231371   0.65399722]
  [0.43048494 0.44583996 0.51626454 ... 0.20504928 0.22966431 0.65831036]
  [0.43951301 0.44373564 0.51750138 ... 0.20722225 0.22620295 0.65961484]]

 [[0.59261135 0.61859566 0.63535746 ... 0.12591744 0.22931167 0.61849258]
  [0.60425068 0.683126

KeyboardInterrupt: 